services:
  db:
    image: docker.io/library/mariadb:10.11
    env_file: .env
    networks:
      - backend-net
    volumes:
      db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  redis:
    image: docker.io/library/redis:7-alpine
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  php-fpm:
    image: localhost/my-custom-php:8.3-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    networks:
      - backend-net
    volumes:
      - ./web-site:/var/www/html:ro,Z
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  web1:
    image: docker.io/library/nginx:1.26-alpine
    networks:
      - frontend-net
      - backend-net
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro,Z
      - ./web-site:/var/www/html:ro,z
    depends_on:
      php-fpm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  web2:
    image: docker.io/library/nginx:1.26-alpine
    networks:
      - frontend-net
      - backend-net
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro,Z
      - ./web-site:/var/www/html:ro,z
    depends_on:
      php-fpm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  proxy:
    image: docker.io/library/haproxy:3.4-alpine
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8404:8404"
    networks:
      - frontend-net
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro,Z
      - ./haproxy/certs:/usr/local/etc/haproxy/certs:ro,Z
    depends_on:
      web1:
        condition: service_healthy
      web2:
        condition: service_healthy
          
    healthcheck:
      test: ["CMD", "haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-c"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
volumes:
  db_data:
